#!/bin/sh

out_file=$1

cat > $out_file <<'EOT'
[
    {riak_kv, [
        {delete_mode, immediate}
    ]},
    {riak_core, [
        {target_n_val, 5},
        {forced_ownership_handoff, 100},
        {handoff_concurrency, 100}
    ]}
].
EOT

