#!/usr/bin/env bash

declare -i uid="$(id -u)"
if [[ $uid != 0 ]]
then
    echo 'Must be run by root user!' 1>&2
    exit 1
fi

curl -s https://packagecloud.io/install/repositories/basho/riak/script.deb.sh | bash
apt-get install riak

declare -r riak_conf=/etc/riak/riak.conf
if [[ ! -f $riak_conf ]]
then
    echo "Could not find $riak_conf file!" 1>&2
    exit 1
fi

# TODO - no copypasta with devrel/gen-riak-conf
cat >> $riak_conf <<EOT
ring_size = 64
search = on
storage_backend = leveldb
anti_entropy = passive
search.solr.start_timeout = 60s
EOT

riak start
riak-admin wait-for-service riak_kv
riak-admin wait-for-service riak_pipe
riak-admin wait-for-service yokozuna

# NB: must exit 0 so we don't use the last exit val
exit 0
