#!/bin/sh

# NB: nothing bash-specific in this file

curl -s https://packagecloud.io/install/repositories/basho/riak/script.deb.sh | sudo bash
sudo apt-get install riak

echo 'search = on' | sudo tee -a /etc/riak/riak.conf
echo 'nodename = riak@127.0.0.1' | sudo tee -a /etc/riak/riak.conf
echo 'storage_backend = multi' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.default = leveldb_backend' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.bitcask_backend.storage_backend = bitcask' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.bitcask_backend.bitcask.data_root = $(platform_data_dir)/bitcask' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.bitcask_backend.bitcask.io_mode = erlang' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.leveldb_backend.storage_backend = leveldb' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.leveldb_backend.leveldb.data_root = $(platform_data_dir)/leveldb' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.leveldb_backend.leveldb.maximum_memory.percent = 30' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.mem_backend.storage_backend = memory' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.mem_backend.memory_backend.ttl = 10s' | sudo tee -a /etc/riak/riak.conf
echo 'multi_backend.mem_backend.memory_backend.max_memory_per_vnode = 4MB' | sudo tee -a /etc/riak/riak.conf

sudo riak start
sudo riak-admin wait-for-service riak_kv

sudo riak-admin bucket-type create phptest_counters '{"props":{"datatype":"counter"}}'
sudo riak-admin bucket-type create phptest_maps '{"props":{"datatype":"map"}}'
sudo riak-admin bucket-type create phptest_sets '{"props":{"datatype":"set"}}'
sudo riak-admin bucket-type create phptest_search '{"props":{}}'
sudo riak-admin bucket-type create phptest_leveldb '{"props":{"backend":"leveldb_backend"}}'
sudo riak-admin bucket-type create hlls '{"props":{"datatype":"hll"}}'

sudo riak-admin bucket-type activate phptest_counters
sudo riak-admin bucket-type activate phptest_maps
sudo riak-admin bucket-type activate phptest_sets
sudo riak-admin bucket-type activate phptest_search
sudo riak-admin bucket-type activate phptest_leveldb
sudo riak-admin bucket-type activate hlls

# NB: must exit 0 so we don't use the last exit val
exit 0
