#!/usr/bin/env bash

declare -i uid="$(id -u)"
if [[ $uid != 0 ]]
then
    echo 'Must be run by root user!' 1>&2
    exit 1
fi

opt_passed='false'
opt_install_riak='false'
opt_start_riak='false'
opt_download_url='unset'

while getopts "isd:" opt; do
    case $opt in
        d)
            opt_download_url="$OPTARG";;
        i)
            opt_passed='true'
            opt_install_riak='true';;
        s)
            opt_passed='true'
            opt_start_riak='true';;
    esac
done

if [[ $opt_passed == 'true' ]]
then
    declare -r install_riak="$opt_install_riak"
    declare -r start_riak="$opt_start_riak"
else
    declare -r install_riak='true'
    declare -r start_riak='true'
fi

if [[ $opt_download_url == 'unset' ]]
then
    declare -r download_url='https://packagecloud.io/install/repositories/basho/riak/script.deb.sh'
else
    declare download_url="$opt_download_url"
    declare -r dpkg_name="${download_url##*/}"
fi

if [[ $install_riak == 'true' ]]
then
    if [[ $download_url == 'rc' ]]
    then
        if [[ -n $RIAK_RC_DOWNLOAD_URL ]]
        then
            download_url="$RIAK_RC_DOWNLOAD_URL"
        else
            echo "Travis CI build configured to look for RC build, but RIAK_RC_DOWNLOAD_URL env var is not set." 1>&2
            exit 1
        fi
    fi

    if [[ $download_url == *.deb.sh ]]
    then
        curl -s "$download_url" | bash
        apt-get install riak
    elif [[ $download_url == *.deb ]]
    then
        curl -O "$download_url"
        dpkg -i "$dpkg_name"
    else
        echo "Don't know how to install from $download_url, exiting!" 1>&2
        exit 1
    fi

    declare -r riak_conf=/etc/riak/riak.conf
    if [[ ! -f $riak_conf ]]
    then
        echo "Could not find $riak_conf file!" 1>&2
        exit 1
    fi

    # TODO - no copypasta with devrel/gen-riak-conf
    cat >> $riak_conf <<EOT
ring_size = 64
search = on
storage_backend = leveldb
anti_entropy = passive
search.solr.start_timeout = 60s
EOT
fi

if [[ $start_riak == 'true' ]]
then
    riak start
    riak-admin wait-for-service riak_kv
    riak-admin wait-for-service riak_pipe
    riak-admin wait-for-service yokozuna
fi

# NB: must exit 0 so we don't use the last exit val
exit 0
